didi/DoKit

DoraemonKit/Src/Core/Category/UIImage+DoraemonKit.m
解决在Podfile中加上use_frameworks!后无法获取到图片的问题
=> 解决获取图片方法错误

DoraemonKit/Src/Core/Util/DoraemonUtil.h
=> 修复沙盒浏览器文件大小显示错误

DoraemonKit/Src/Core/Plugin/DeleteLocalData/DoraemonDeleteLocalDataViewController.m, DoraemonKit/Src/Core/Plugin/Sanbox/VC/DoraemonSandboxCell.m, DoraemonKit/Src/Core/Plugin/Sanbox/VC/DoraemonSandboxViewController.m, DoraemonKit/Src/Core/Util/DoraemonUtil.h, DoraemonKit/Src/Core/Util/DoraemonUtil.m
1、优化文件名过长时和文件大小重叠的问题
2、修复清理本地数据，权限问题失败的问题。
=> 修复清理本地数据问题和优化文件名过长时的展示

Android/app/src/main/java/com/didichuxing/doraemondemo/MainActivity.java, Android/app/src/main/res/layout/activity_main.xml, Android/app/src/main/res/values/styles.xml, Android/doraemonkit/src/main/java/com/didichuxing/doraemonkit/DoraemonHooker.java, Android/doraemonkit/src/main/java/com/didichuxing/doraemonkit/DoraemonKit.java, Android/doraemonkit/src/main/java/com/didichuxing/doraemonkit/kit/blockmonitor/BlockListFragment.java, Android/doraemonkit/src/main/java/com/didichuxing/doraemonkit/ui/base/FloatPageManager.java, Android/doraemonkit/src/main/res/layout/dk_fragment_block_list.xml
[#52](https://github.com/didi/DoraemonKit/issues/52)
[#53](https://github.com/didi/DoraemonKit/issues/53)
卡顿详情增加了ScrollView；
增加动态显示隐藏悬浮窗的方法。
=> 解决#52 #53的问题

Android/app/src/main/java/com/didichuxing/doraemondemo/MainActivity.java, Android/app/src/main/res/layout/activity_main.xml, Android/app/src/main/res/values/styles.xml, Android/doraemonkit/src/main/java/com/didichuxing/doraemonkit/DoraemonHooker.java, Android/doraemonkit/src/main/java/com/didichuxing/doraemonkit/DoraemonKit.java, Android/doraemonkit/src/main/java/com/didichuxing/doraemonkit/kit/blockmonitor/BlockListFragment.java, Android/doraemonkit/src/main/java/com/didichuxing/doraemonkit/ui/base/FloatPageManager.java, Android/doraemonkit/src/main/res/layout/dk_fragment_block_list.xml
=> Revert "解决#52 #53的问题"

DoraemonKit.podspec, iOS/DoraemonKit/Src/Core/Plugin/ANR/Function/DoraemonANRManager.m, iOS/DoraemonKit/Src/Core/Util/DoraemonStatisticsUtil.m, iOS/DoraemonKitDemo/Podfile.lock
除demo外，只有一处网络请求，没有必要依赖 AFNetworking
=> remove dependency 'AFNetworking'

iOS/DoraemonKit/Src/Core/Util/DoraemonStatisticsUtil.m
https://github.com/didi/DoraemonKit/pull/84 中有类型错误的问题  @yixiangboy
=> type error

iOS/DoraemonKit/Src/Core/Entry/Home/View/DoraemonHomeSectionView.m, iOS/DoraemonKit/Src/Core/Plugin/Protocol/DoraemonPluginProtocol.h
将点击的按钮的itemdata返回来 使用itemdata中的desc 和 title 字段
=> 将itemData返回来

iOS/DoraemonKit/Src/Core/Plugin/H5/DoraemonH5ViewController.m
h5 输入法的一点小改善。去掉自动修正，去掉自动大写，更好的键盘
=> H5 任意门输入法适配

iOS/DoraemonKit/Src/Core/Plugin/Sanbox/VC/DoraemonSanboxDetailViewController.m
=> 修复预览本地视频不能全屏幕播放问题

iOS/DoraemonKit/Src/Core/Plugin/AppInfo/DoraemonAppInfoUtil.h, iOS/DoraemonKit/Src/Core/Plugin/AppInfo/DoraemonAppInfoUtil.m, iOS/DoraemonKit/Src/Core/Plugin/Sanbox/VC/DoraemonSandboxViewController.m
viewDidLoad 拿到的当前controller 的尺寸不是对的。需要手动减或者在viewDidLayoutSubviews 方法设置尺寸
=> 修复浏览沙盒文件不能看到底部文件问题。

Android/doraemonkit/src/main/java/com/didichuxing/doraemonkit/kit/common/PerformanceDataManager.java, Android/doraemonkit/src/main/java/com/didichuxing/doraemonkit/kit/custom/PageDataFragment.java, Android/doraemonkit/src/main/java/com/didichuxing/doraemonkit/kit/custom/PageDataItem.java, Android/doraemonkit/src/main/java/com/didichuxing/doraemonkit/kit/custom/PageDataItemAdapter.java, Android/doraemonkit/src/main/java/com/didichuxing/doraemonkit/kit/custom/RealTimePerformDataFloatPage.java, Android/doraemonkit/src/main/java/com/didichuxing/doraemonkit/kit/custom/UploadMonitorInfoBean.java, Android/doraemonkit/src/main/java/com/didichuxing/doraemonkit/kit/custom/UploadMonitorItem.java, Android/doraemonkit/src/main/java/com/didichuxing/doraemonkit/kit/network/bean/NetflowInfo.java
=> bug fix 141

Android/doraemonkit/src/main/java/com/didichuxing/doraemonkit/kit/weaknetwork/ByteCountBufferedSink.java, Android/doraemonkit/src/main/java/com/didichuxing/doraemonkit/kit/weaknetwork/WeakNetworkManager.java
1.之前的限速设置不支持设置0K/s，现在解决了这个问题，0则不限速；
2.之前的上传限速只有参数是文件才会生效，现在其它类型的参数也会生效。
=> Android - 模拟弱网优化

iOS/DoraemonKit/Src/Core/Plugin/NetFlow/Detail/DoraemonNetFlowDetailCell.m
fix: 流量监控详情页面中 UITextView 产生的滑动冲突
fix: 流量监控详情页面展示问题(Cell 高度计算错误)
=> fix: 流量监控详情页面中 UITextView 产生的滑动冲突; 流量监控详情页面展示问题(Cell 高度计算错误)

iOS/DoraemonKit/Src/Core/Plugin/ViewAlign/Function/DoraemonViewAlignView.m
=> 统一布局颜色定义，方便检查黑色界面

iOS/DoraemonKit/Src/GPS/Function/DoraemonGPSMocker.m
=> 因GPS低版本，缺少方法导致的崩溃

Android/doraemonkit/src/main/java/com/didichuxing/doraemonkit/kit/dbdebug/DbDebugFragment.java, Android/doraemonkit/src/main/java/com/didichuxing/doraemonkit/kit/dbdebug/DbDebugKit.java, Android/doraemonkit/src/main/java/com/didichuxing/doraemonkit/util/netstate/Constants.java, Android/doraemonkit/src/main/java/com/didichuxing/doraemonkit/util/netstate/INetwork.java, Android/doraemonkit/src/main/java/com/didichuxing/doraemonkit/util/netstate/NetChangeObserver.java, Android/doraemonkit/src/main/java/com/didichuxing/doraemonkit/util/netstate/NetStateReceiver.java, Android/doraemonkit/src/main/java/com/didichuxing/doraemonkit/util/netstate/NetType.java, Android/doraemonkit/src/main/java/com/didichuxing/doraemonkit/util/netstate/NetWork.java, Android/doraemonkit/src/main/java/com/didichuxing/doraemonkit/util/netstate/NetWorkCallbackImpl.java, Android/doraemonkit/src/main/java/com/didichuxing/doraemonkit/util/netstate/NetworkManager.java, Android/doraemonkit/src/main/java/com/didichuxing/doraemonkit/util/netstate/NetworkMethod.java, Android/doraemonkit/src/main/java/com/didichuxing/doraemonkit/util/netstate/NetworkUtil.java
1. 随开启app启动DBView功能
2. 切换wifi,自动重启.支持Android21+
=> 优化DBView功能

iOS/DoraemonKit/Src/Core/Plugin/Sanbox/VC/DB/DoraemonDBShowView.m
使用 UITextView 替换 UILabel 修复字段长无法展示全的问题
=> fix: DB 字段太长无法展示全的问题

iOS/DoraemonKit/Src/Core/Manager/DoraemonManager.m
优化根据开关判断是否开启流量监控，因为有 “在程序启动的时候，需要进行流量检测的应用场景”。
=> 优化根据开关判断是否开启流量监控

iOS/DoraemonKit/Src/Core/Plugin/ANR/Function/DoraemonPingThread.m, iOS/DoraemonKit/Src/Core/Plugin/SubThreadUICheck/Function/UIView+DoraemonSubThreadUICheck.m
相关issue: https://github.com/didi/DoraemonKit/issues/346
=> feat: 支持generate_multiple_pod_projects参数

Android/doraemonkit/src/main/java/com/didichuxing/doraemonkit/kit/network/bean/NetworkRecord.java, Android/doraemonkit/src/main/java/com/didichuxing/doraemonkit/kit/network/ui/NetworkDetailView.java
Signed-off-by: Desert <zyallday@qiyi.com>
=> feat: 流量拦截json显示优化

iOS/DoraemonKit/Src/Core/Plugin/Common/AppInfo/DoraemonAppInfoViewController.h, iOS/DoraemonKit/Src/Core/Plugin/Common/AppInfo/DoraemonAppInfoViewController.m, iOS/DoraemonKitDemo/DoraemonKitDemo/DoKitAppDelegate.m, iOS/DoraemonKitDemo/Podfile, iOS/DoraemonKitDemo/Podfile.lock
=> 支持自定义添加APP信息

iOS/Swift/DoKitSwift/Src/Entry/Entry/EntryWindow.swift, iOS/Swift/DoKitSwift/Src/Fountion/CommonUI/CellBtn/CellButton.swift, iOS/Swift/DoKitSwift/Src/Fountion/CommonUI/VC/BaseBigTitleView.swift, iOS/Swift/DoKitSwift/Src/Fountion/CommonUI/VC/BaseViewController.swift, iOS/Swift/DoKitSwift/Src/Fountion/Extension/UIImageExtensions.swift, iOS/Swift/DoKitSwift/Src/Plugins/Common/AppSetting/AppSettingPlugin.swift, iOS/Swift/DoKitSwift/Src/Plugins/Common/DelSanbox/DelSanboxPlugin.swift, iOS/Swift/DoKitSwift/Src/Plugins/Common/MainThreadChecker/MainThreadCheckerPlugin.swift, iOS/Swift/DoKitSwift/Src/Plugins/UI/ColorPick/ColorPickPlugin.swift, iOS/Swift/DoKitSwift/Src/Plugins/UI/ColorPick/Function/ColorPickInfoView.swift, iOS/Swift/DoKitSwift/Src/Plugins/UI/ViewAlign/Function/ViewAlignView.swift, iOS/Swift/DoKitSwift/Src/Plugins/UI/ViewAlign/ViewAlignPlugin.swift, iOS/Swift/DoKitSwift/Src/Plugins/UI/ViewCheck/Function/ViewCheckView.swift, iOS/Swift/DoKitSwift/Src/Plugins/UI/ViewCheck/ViewCheckPlugin.swift, iOS/Swift/DoKitSwift/Src/Plugins/UI/ViewMetrics/ViewMetricsPlugin.swift
- Support all scale
- Support dark mode
````swift
let image = UIImage.dynamic(with: UIImage("doraemon_close"), dark: UIImage("doraemon_close_dark"))
````
````swift
let image = DKImage(named: "doraemon_close")
````
=> Code refactoring for dokitImageName

Android/kotlin/doraemonkit/src/main/java/com/didichuxing/doraemonkit/kit/blockmonitor/BlockListAdapter.kt, Android/kotlin/doraemonkit/src/main/java/com/didichuxing/doraemonkit/kit/blockmonitor/BlockListFragment.kt, Android/kotlin/doraemonkit/src/main/java/com/didichuxing/doraemonkit/kit/blockmonitor/BlockMonitorFragment.kt, Android/kotlin/doraemonkit/src/main/java/com/didichuxing/doraemonkit/kit/blockmonitor/BlockMonitorKit.kt, Android/kotlin/doraemonkit/src/main/java/com/didichuxing/doraemonkit/kit/blockmonitor/bean/BlockInfo.kt, Android/kotlin/doraemonkit/src/main/java/com/didichuxing/doraemonkit/kit/blockmonitor/core/BlockCanaryUtils.kt, Android/kotlin/doraemonkit/src/main/java/com/didichuxing/doraemonkit/kit/blockmonitor/core/BlockMonitorManager.kt, Android/kotlin/doraemonkit/src/main/java/com/didichuxing/doraemonkit/kit/blockmonitor/core/MonitorCore.kt, Android/kotlin/doraemonkit/src/main/java/com/didichuxing/doraemonkit/kit/blockmonitor/core/OnBlockInfoUpdateListener.kt, Android/kotlin/doraemonkit/src/main/java/com/didichuxing/doraemonkit/kit/blockmonitor/core/StackSampler.kt, Android/kotlin/doraemonkit/src/main/java/com/didichuxing/doraemonkit/kit/core/BaseFragment.kt, Android/kotlin/doraemonkit/src/main/java/com/didichuxing/doraemonkit/kit/core/SettingItem.kt, Android/kotlin/doraemonkit/src/main/java/com/didichuxing/doraemonkit/kit/core/UniversalActivity.kt, Android/kotlin/doraemonkit/src/main/java/com/didichuxing/doraemonkit/util/NotificationUtils.kt, Android/kotlin/doraemonkit/src/main/java/com/didichuxing/doraemonkit/widget/recyclerview/AbsRecyclerAdapter.kt, Android/kotlin/doraemonkit/src/main/java/com/didichuxing/doraemonkit/widget/recyclerview/AbsViewBinder.kt, Android/kotlin/doraemonkit/src/main/res/layout/dk_fragment_block_list.xml, Android/kotlin/doraemonkit/src/main/res/layout/dk_fragment_block_monitor_index.xml, Android/kotlin/doraemonkit/src/main/res/layout/dk_item_block_list.xml
BlockMonitorManager 依赖 监控检测、跳转耗时的相关代码加了TODO，需要等相应模块开发好后，再添加关联代码
=> [kotlin]-[卡顿检测]-[实现卡顿相关功能并完成自测]

Android/kotlin/doraemonkit/src/main/java/com/didichuxing/doraemonkit/config/PerformanceSpInfoConfig.kt, Android/kotlin/doraemonkit/src/main/java/com/didichuxing/doraemonkit/kit/core/UniversalActivity.kt, Android/kotlin/doraemonkit/src/main/java/com/didichuxing/doraemonkit/kit/largepicture/LargeImageInfo.kt, Android/kotlin/doraemonkit/src/main/java/com/didichuxing/doraemonkit/kit/largepicture/LargeImageListAdapter.kt, Android/kotlin/doraemonkit/src/main/java/com/didichuxing/doraemonkit/kit/largepicture/LargeImageListFragment.kt, Android/kotlin/doraemonkit/src/main/java/com/didichuxing/doraemonkit/kit/largepicture/LargePictureFragment.kt, Android/kotlin/doraemonkit/src/main/java/com/didichuxing/doraemonkit/kit/largepicture/LargePictureItemAdapter.kt, Android/kotlin/doraemonkit/src/main/java/com/didichuxing/doraemonkit/kit/largepicture/LargePictureKit.kt, Android/kotlin/doraemonkit/src/main/java/com/didichuxing/doraemonkit/kit/largepicture/LargePictureManager.kt, Android/kotlin/doraemonkit/src/main/java/com/didichuxing/doraemonkit/util/ClipboardUtils.kt, Android/kotlin/doraemonkit/src/main/res/layout/dk_fragment_large_img_list.xml, Android/kotlin/doraemonkit/src/main/res/layout/dk_fragment_performance_large_picture_setting.xml, Android/kotlin/doraemonkit/src/main/res/layout/dk_item_large_img_list.xml, Android/kotlin/doraemonkit/src/main/res/layout/dk_item_setting.xml
[kotlin改造完成,暂时频闭了网络监控的开关,需要等待网络模块完成]
=> Kotlin-大图检测

iOS/Swift/DoKitSwift/Src/DoKit.swift, iOS/Swift/DoKitSwift/Src/Entry/Home/HomeViewController.swift, iOS/Swift/DoKitSwift/Src/Plugins/Base/Plugin.swift, iOS/Swift/DoKitSwift/Src/Plugins/Common/AppInfo/AppInfoPlugin.swift, iOS/Swift/DoKitSwift/Src/Plugins/Common/AppSetting/AppSettingPlugin.swift, iOS/Swift/DoKitSwift/Src/Plugins/Common/DelSanbox/DelSanboxPlugin.swift, iOS/Swift/DoKitSwift/Src/Plugins/Common/H5/H5Plugin.swift, iOS/Swift/DoKitSwift/Src/Plugins/Common/Logs/LogPlugin.swift, iOS/Swift/DoKitSwift/Src/Plugins/Performance/ANR/ANRPlugin.swift, iOS/Swift/DoKitSwift/Src/Plugins/Performance/Crash/CrashPlugin.swift, iOS/Swift/DoKitSwift/Src/Plugins/Performance/LaunchTime/LaunchTimePlugin.swift, iOS/Swift/DoKitSwift/Src/Plugins/Performance/MainThreadChecker/MainThreadCheckerPlugin.swift, iOS/Swift/DoKitSwift/Src/Plugins/UI/ColorPick/ColorPickPlugin.swift, iOS/Swift/DoKitSwift/Src/Plugins/UI/ViewAlign/ViewAlignPlugin.swift, iOS/Swift/DoKitSwift/Src/Plugins/UI/ViewCheck/ViewCheckPlugin.swift, iOS/Swift/DoKitSwift/Src/Plugins/UI/ViewMetrics/ViewMetricsPlugin.swift, iOS/Swift/DoKitSwiftDemo/DoKitSwiftDemo/AppDelegate.swift
PluginModule 使用 enum ，避免硬编码造成错误（这个支持外部定义 PluginModule）
=> refactor: refactor PluginModule

Android/kotlin/doraemonkit/src/main/java/com/didichuxing/doraemonkit/config/GpsMockConfig.kt, Android/kotlin/doraemonkit/src/main/java/com/didichuxing/doraemonkit/kit/core/UniversalActivity.kt, Android/kotlin/doraemonkit/src/main/java/com/didichuxing/doraemonkit/kit/gpsmock/GpsMockFragment.kt, Android/kotlin/doraemonkit/src/main/java/com/didichuxing/doraemonkit/kit/gpsmock/GpsMockKit.kt, Android/kotlin/doraemonkit/src/main/java/com/didichuxing/doraemonkit/util/WebViewUtil.kt, Android/kotlin/doraemonkit/src/main/res/layout/dk_fragment_gps_mock.xml
Signed-off-by: Desert <zyallday@gmail.com>
=> [kotlin]-[位置模拟]-[增加位置模拟功能，自测通过]

iOS/Swift/DoKitSwift/Src/Entry/Home/HomeViewController.swift, iOS/Swift/DoKitSwift/Src/Fountion/CommonUI/CellBtn/CellButton.swift, iOS/Swift/DoKitSwift/Src/Fountion/CommonUI/CellBtn/CellSwitch.swift, iOS/Swift/DoKitSwift/Src/Fountion/CommonUI/VC/BaseBigTitleView.swift, iOS/Swift/DoKitSwift/Src/Fountion/CommonUI/VC/BaseViewController.swift, iOS/Swift/DoKitSwift/Src/Fountion/CommonUI/VC/FileListViewController.swift, iOS/Swift/DoKitSwift/Src/Fountion/CommonUI/VC/FilePreviewController.swift, iOS/Swift/DoKitSwift/Src/Fountion/Extension/UIColorExtensions.swift, iOS/Swift/DoKitSwift/Src/Plugins/Common/AppInfo/AppInfoViewController.swift, iOS/Swift/DoKitSwift/Src/Plugins/Common/DelSanbox/DelSanboxViewController.swift, iOS/Swift/DoKitSwift/Src/Plugins/Common/H5/DefaultWebViewController.swift, iOS/Swift/DoKitSwift/Src/Plugins/Common/H5/H5ViewController.swift, iOS/Swift/DoKitSwift/Src/Plugins/Common/H5/QRCode/QRScanView.swift, iOS/Swift/DoKitSwift/Src/Plugins/Common/Logs/ViewController/LogViewController.swift, iOS/Swift/DoKitSwift/Src/Plugins/Performance/ANR/ANRViewController.swift, iOS/Swift/DoKitSwift/Src/Plugins/Performance/ANR/Detail/ANRDetailViewController.swift, iOS/Swift/DoKitSwift/Src/Plugins/Performance/ANR/List/ANRListCell.swift, iOS/Swift/DoKitSwift/Src/Plugins/Performance/ANR/List/ANRListViewController.swift, iOS/Swift/DoKitSwift/Src/Plugins/Performance/Crash/CrashViewController.swift, iOS/Swift/DoKitSwift/Src/Plugins/Performance/Crash/List/CrashListCell.swift, iOS/Swift/DoKitSwift/Src/Plugins/Performance/Crash/List/SandboxListViewController.swift, iOS/Swift/DoKitSwift/Src/Plugins/Performance/LaunchTime/LaunchTimeViewController.swift, iOS/Swift/DoKitSwift/Src/Plugins/Performance/MainThreadChecker/MainThreadCheckerViewController.swift, iOS/Swift/DoKitSwift/Src/Plugins/UI/ColorPick/Function/ColorPickInfoView.swift
1. 使用 autolayout 实现 CellSwitch
2. 使用 swift 风格的api
=> 使用 autolayout 实现 CellSwitch && 使用 swift 风格的api

Android/kotlin/doraemonkit/src/main/java/com/didichuxing/doraemonkit/kit/core/AbsDokitView.kt, Android/kotlin/doraemonkit/src/main/java/com/didichuxing/doraemonkit/kit/loginfo/LogExportDialog.kt, Android/kotlin/doraemonkit/src/main/java/com/didichuxing/doraemonkit/kit/loginfo/LogInfoDokitView.kt, Android/kotlin/doraemonkit/src/main/java/com/didichuxing/doraemonkit/kit/loginfo/LogInfoKit.kt, Android/kotlin/doraemonkit/src/main/java/com/didichuxing/doraemonkit/kit/loginfo/LogInfoManager.kt, Android/kotlin/doraemonkit/src/main/java/com/didichuxing/doraemonkit/kit/loginfo/LogItemAdapter.kt, Android/kotlin/doraemonkit/src/main/java/com/didichuxing/doraemonkit/kit/loginfo/LogLine.kt, Android/kotlin/doraemonkit/src/main/java/com/didichuxing/doraemonkit/kit/loginfo/LogcatReader.kt, Android/kotlin/doraemonkit/src/main/java/com/didichuxing/doraemonkit/kit/loginfo/helper/LogcatHelper.kt, Android/kotlin/doraemonkit/src/main/java/com/didichuxing/doraemonkit/kit/loginfo/helper/RuntimeHelper.kt, Android/kotlin/doraemonkit/src/main/java/com/didichuxing/doraemonkit/kit/loginfo/reader/AbsLogcatReader.kt, Android/kotlin/doraemonkit/src/main/java/com/didichuxing/doraemonkit/kit/loginfo/reader/LogcatReaderLoader.kt, Android/kotlin/doraemonkit/src/main/java/com/didichuxing/doraemonkit/kit/loginfo/reader/SingleLogcatReader.kt, Android/kotlin/doraemonkit/src/main/java/com/didichuxing/doraemonkit/kit/loginfo/util/SearchCriteria.kt, Android/kotlin/doraemonkit/src/main/java/com/didichuxing/doraemonkit/kit/loginfo/util/StringUtil.kt, Android/kotlin/doraemonkit/src/main/java/com/didichuxing/doraemonkit/kit/loginfo/util/TagColorUtil.kt, Android/kotlin/doraemonkit/src/main/java/com/didichuxing/doraemonkit/widget/recyclerview/AbsRecyclerAdapter.kt, Android/kotlin/doraemonkit/src/main/java/com/didichuxing/doraemonkit/widget/titlebar/LogTitleBar.kt, Android/kotlin/doraemonkit/src/main/res/layout/dk_float_log_info.xml, Android/kotlin/doraemonkit/src/main/res/layout/dk_item_log.xml, Android/kotlin/doraemonkit/src/main/res/layout/dk_log_title_bar.xml
Signed-off-by: Desert <zyallday@gmail.com>
=> [kotlin]-[日志]-[完成日志模块功能,已自测]

iOS/Swift/DoKitSwift/Src/Plugins/Performance/LaunchTime/LaunchTime.swift, iOS/Swift/DoKitSwiftDemo/DoKitSwiftDemo/AppDelegate.swift
=> 删除 DoKit.didFinishLaunching

Android/java/doraemonkit/src/main/java/com/didichuxing/doraemonkit/kit/uiperformance/UIPerformanceManager.java
=> #628 使用trycatch避免调用draw方法崩溃,不显示的View不调用draw方法

iOS/DoraemonKit/Src/Core/Category/UIImage+Doraemon.m, iOS/DoraemonKit/Src/GPS/Function/DoraemonGPSMocker.m
=> Revert "修改1x图片不显示的问题"

Android/java/doraemonkit/src/main/java/com/didichuxing/doraemonkit/kit/crash/CrashCaptureManager.java, Android/java/doraemonkit/src/main/java/com/didichuxing/doraemonkit/util/ImageUtil.java, Android/java/doraemonkit/src/main/res/values-en-rUS/strings.xml, Android/java/doraemonkit/src/main/res/values-zh-rCN/strings.xml, Android/java/doraemonkit/src/main/res/values-zh-rTW/strings.xml, Android/java/doraemonkit/src/main/res/values/strings.xml
=> 在Crash日志的基础上加入了崩溃截屏功能

iOS/DoraemonKit/Src/Core/Entry/Home/Cell/DoraemonHomeCell.h, iOS/DoraemonKit/Src/Core/Entry/Home/Cell/DoraemonHomeCell.m, iOS/DoraemonKit/Src/Core/Entry/Home/DoraemonHomeViewController.m, iOS/DoraemonKit/Src/Core/Entry/Home/Settings/KitManager/DoraemonKitManagerViewController.m, iOS/DoraemonKit/Src/Core/Entry/Home/Settings/KitManager/View/DoraemonKitManagerCell.h, iOS/DoraemonKit/Src/Core/Entry/Home/Settings/KitManager/View/DoraemonKitManagerCell.m, iOS/DoraemonKit/Src/Core/Manager/DoraemonManager.h, iOS/DoraemonKit/Src/Core/Manager/DoraemonManager.m, iOS/DoraemonKitDemo/DoraemonKitDemo/DoKitAppDelegate.m, iOS/DoraemonKitDemo/Podfile.lock
=> 支持自定义插件的图标（传入UIImage）

Flutter/lib/ui/dokit_app.dart
=> 提供设置navigatorKey参数

iOS/DoraemonKit/Src/Core/Manager/DoraemonManager.h, iOS/DoraemonKit/Src/Core/Manager/DoraemonManager.m, iOS/DoraemonKit/Src/Core/Network/Interceptor/DoraemonNSURLProtocol.m, iOS/DoraemonKit/Src/Core/Plugin/Platform/Mock/Function/DoraemonMockManager.m
=> feat: iOS支持mockDomain自定义

iOS/DoraemonKit/Src/Core/Define/DoraemonDefine.h
=> fix: 修改DoKitVersion

iOS/DoraemonKit/Src/Core/Category/UIViewController+Doraemon.m
<a href="https://sm.ms/image/ikfR9zCWKFgDvxl" target="_blank"><img src="https://i.loli.net/2021/03/18/ikfR9zCWKFgDvxl.png"  width="375" height="812"/></a>
修复导航栏可能导致的安全区域问题
=> feat:修复导航栏可能导致的安全区域问题

Web/packages/core/dist/index.js, Web/packages/core/src/common/components/card.vue, Web/packages/core/src/common/components/top-bar.vue, Web/packages/core/src/common/components/version.vue, Web/packages/core/src/components/container.vue, Web/packages/core/src/components/index.vue, Web/packages/utils/dist/dokit.js, Web/packages/web/dist/dokit.js, Web/packages/web/src/feature.js, Web/playground/index.html
=> feat: refactor web ui

iOS/DoraemonKit/Src/MLeaksFinder/Function/Extra/DoraemonMemoryLeakData.h, iOS/DoraemonKit/Src/MLeaksFinder/Function/Extra/DoraemonMemoryLeakData.m
https://github.com/didi/DoraemonKit/issues/770
=> Add memory leak listener

Android/java/app/src/debug/java/com/didichuxing/doraemondemo/App.kt, Android/java/doraemonkit-no-op/src/main/java/com/didichuxing/doraemonkit/DoKit.kt, Android/java/doraemonkit-no-op/src/main/java/com/didichuxing/doraemonkit/DoraemonKit.kt, Android/java/doraemonkit-no-op/src/main/java/com/didichuxing/doraemonkit/kit/network/okhttp/interceptor/DokitExtInterceptor.kt, Android/java/doraemonkit-no-op/src/main/java/com/didichuxing/doraemonkit/kit/performance/PerformanceValueListener.kt, Android/java/doraemonkit/src/main/java/com/didichuxing/doraemonkit/DoKit.kt, Android/java/doraemonkit/src/main/java/com/didichuxing/doraemonkit/DoKitReal.kt, Android/java/doraemonkit/src/main/java/com/didichuxing/doraemonkit/DoraemonKit.kt, Android/java/doraemonkit/src/main/java/com/didichuxing/doraemonkit/aop/OkHttpHook.java, Android/java/doraemonkit/src/main/java/com/didichuxing/doraemonkit/aop/urlconnection/HttpUrlConnectionProxyUtil.java, Android/java/doraemonkit/src/main/java/com/didichuxing/doraemonkit/kit/network/okhttp/interceptor/DokitExtInterceptor.kt, Android/java/doraemonkit/src/main/java/com/didichuxing/doraemonkit/kit/performance/PerformanceDataManager.java, Android/java/doraemonkit/src/main/java/com/didichuxing/doraemonkit/kit/performance/PerformanceValueListener.kt
1.添加cpu，内存，FPS回调
2.添加网络扩展拦截器，可以自定义拦截器操作
=> Android : 1.添加cpu，内存，FPS回调  2.添加网络扩展拦截器，可以自定义拦截器操作

Web/packages/web/src/feature.js, Web/packages/web/src/plugins/align-ruler/align-ruler.vue, Web/packages/web/src/plugins/align-ruler/index.js, Web/packages/web/src/plugins/align-ruler/info-box.vue
功能背景：对齐标尺可以在Web端更方便地实现组件对齐、测量等功能
原理：检测当前鼠标位置，绘制标尺，同时展示位置信息
=> 【DoKit&北大开源实践】-【DoKit For Web】- 对齐标尺

Web/package.json, Web/packages/core/src/common/components/top-bar.vue, Web/packages/core/src/components/router-container.vue, Web/packages/core/src/index.js
=> 【DoKit For Web】-修改面板全局标题

Android/dokit/src/main/java/com/didichuxing/doraemonkit/kit/loginfo/util/StringUtil.java
=> Fix typo in StringUtil.java

iOS/DoraemonKit/Src/Core/Base/DoraemonBaseViewController.m, iOS/DoraemonKit/Src/Core/Plugin/Common/NSUserDefaults/ViewControllers/DoraemonNSUserDefaultsViewController.m, iOS/DoraemonKit/Src/Core/Plugin/Common/Sanbox/VC/DoraemonSandboxViewController.m
1. Fix UserDefaults search
2. Dark mode
3. Sandbox file sort
=> fix(iOS): UserDefaults search

Android/app/build.gradle, Android/app/src/main/java/com/didichuxing/doraemondemo/MainDebugActivityOkhttpV3.kt, Android/app/src/main/res/layout/activity_main.xml, Android/buildSrc/src/main/kotlin/com/didichuxing/doraemonkit/plugin/classtransformer/BigImgClassTransformer.kt, Android/config.gradle, Android/dokit-plugin/src/main/kotlin/com/didichuxing/doraemonkit/plugin/classtransformer/BigImgClassTransformer.kt, Android/dokit/build.gradle, Android/dokit/src/main/java/com/didichuxing/doraemonkit/aop/bigimg/coil/CoilHook.java, Android/dokit/src/main/java/com/didichuxing/doraemonkit/aop/bigimg/coil/DokitCoilTransformation.java
=> add big image detect for coil

DoraemonKit.podspec, iOS/DoraemonKit/Src/Core/Util/fishhook/doraemon_fishhook.c, iOS/Podfile.lock
=> fix(iOS): vm_protect() force shared library const data copy memory page

Android/dokit/src/main/java/com/didichuxing/doraemonkit/kit/core/NormalDoKitViewManager.kt
=> fix: 修复取色器退到后台后的crash问题

Android/dokit/src/main/java/com/didichuxing/doraemonkit/kit/sysinfo/SysInfoFragment.java, Android/dokit/src/main/java/com/didichuxing/doraemonkit/util/DokitDeviceUtils.java
=> App信息面板增加WebView Chrome内核版本信息

Android/dokit/src/main/java/com/didichuxing/doraemonkit/kit/core/DokitViewManager.kt, Android/dokit/src/main/java/com/didichuxing/doraemonkit/kit/core/NormalDoKitViewManager.kt, Android/dokit/src/main/java/com/didichuxing/doraemonkit/kit/core/SystemDoKitViewManager.kt
对普通的浮标模式添加DokitViewAttachedListener支持，以兼容系统浮标的DokitViewAttachedListener
=> fix:普通的浮标模式兼容系统浮标的DokitViewAttachedListener

Web/packages/web/src/common/info-card.vue, Web/packages/web/src/components/ScanerComponent.vue
=> feat: web代码优化
