- DoraemonKit/Src/Core/Plugin/Memory/Function/DoraemonMemoryUtil.m
reference: 
1. https://github.com/aozhimin/iOS-Monitor-Platform/issues/14
2. http://www.samirchen.com/ios-app-memory-usage/
> use phys_footprint to get instruments memory usage

- iOS/DoraemonKit/Src/Core/Plugin/ViewMetrics/Function/DoraemonViewMetricsConfig.m
- iOS/DoraemonKit/Src/Core/Plugin/ViewMetrics/Function/UIView+DoraemonViewMetrics.m
参见issue：[iOS 『元素边框线』对于UIStatusBarWindow的遗漏](https://github.com/didi/DoraemonKit/issues/30)
> UI元素辅助线功能遗漏对UIStatusBarWindow判断的修复

- iOS/DoraemonKit/Src/Core/Base/DoraemonStatusBarViewController.h
- iOS/DoraemonKit/Src/Core/Base/DoraemonStatusBarViewController.m
- iOS/DoraemonKit/Src/Core/Entry/DoraemonEntryView.m
主要问题在iOS9.0的系统中，新建的window设置的rootViewController默认没有显示状态栏，我在DoraemonEntryView里面加了个判断，但是还有发现的已知问题没有解决，如果开启帧率或者cpu检查等功能，状态栏还是没有没有显示，目前这样至少保证了关闭所有功能之后能够显示正常，剩下的问题还需要花时间去找原因
> fix:在iOS9.0系统中直接不显示状态栏的问题，但是在开启cpu监听等状态时，还是不显示状态栏，暂未找到解决版本

- Android/doraemonkit/src/main/java/com/didichuxing/doraemonkit/kit/common/PerformanceDataManager.java
目前所有的性能数据都存储到了同一目录下，导致多个项目都使用了DoraemonKit时，文件会冲突。
这个pr里面把数据存储到了 /Android/data/packageName/files/doraemon 下，既能通过文件管理器直接访问，又避免了多个app文件冲突的问题。
> 性能数据保存到ExternalFilesDir

- Android/app/src/main/java/com/didichuxing/doraemondemo/MainActivity.java
- Android/doraemonkit/src/main/java/com/didichuxing/doraemonkit/kit/network/aspect/AopUtils.java
OkHttp添加日志拦截去除依赖流量监测开关，因为在实际场景中，OkHttpClient只会创建一次，当打开流量日志开关的时候，OkHttpClient已经创建过了，不会走Builder.build因此拦截不到
> fix(OkHttpAspect):OkHttp添加日志拦截去除依赖流量监测开关

- Android/build.gradle
- Android/doraemonkit/build.gradle
- Android/gradle/wrapper/gradle-wrapper.properties
因为AS3.2以上需要NDK需要 android-gradle版本大于3.2.0 否则会报No toolchains found in the NDK toolchains folder for ABI with prefix: mips64el-linux-android
> fix:升级android-gradle 及 gradle版本

- Android/doraemonkit/src/main/java/com/didichuxing/doraemonkit/util/DatabaseUtil.java
DatabaseDetailFragment 展示本地sqlite文件内容，如果column类型是FIELD_TYPE_BLOB，调用Cursor.getString()会直接报错，建议先通过cursor.getType()先判断column类型，再调用cursor.getString()或者cursor.getBlob() 取值。
> 【修复】#196 在Android设备上浏览数据库表的时候，带有BLOB类型的不能浏览

- Android/doraemonkit/src/main/java/com/didichuxing/doraemonkit/kit/parameter/frameInfo/FrameInfoFragment.java
如果之前没有点进去过CPU,RAM页面，帧率显示页面将不能保存帧率数据，原因在于帧率页面没有初始化`PerformanceDataManager `,所以在帧率页面加上了初始化操作
> 修复帧率Fragment 不能保存数据问题

- iOS/DoraemonKit/Src/Core/Manager/DoraemonManager.m
`#import "DoraemonGPSMocker.h"` is enclosed with `DoraemonWithGPS` define check:
```objc
#if DoraemonWithGPS
#import "DoraemonGPSMocker.h"
#endif
```
but the usage of `DoraemonGPSMocker` in line 126 is not checked with `DoraemonWithGPS` definition, which may cause build error without `DoraemonKit/WithGPS` integrated.
```objc
[[DoraemonCacheManager sharedInstance] saveMemorySwitch:NO];
[[DoraemonCacheManager sharedInstance] saveNetFlowSwitch:NO];
//开启mockGPS功能
if ([[DoraemonCacheManager sharedInstance] mockGPSSwitch]) {
CLLocationCoordinate2D coordinate = [[DoraemonCacheManager sharedInstance] mockCoordinate];
if (coordinate.longitude>0 && coordinate.latitude>0) {
CLLocation *loc = [[CLLocation alloc] initWithLatitude:coordinate.latitude longitude:coordinate.longitude];
[[DoraemonGPSMocker …
```
> FIX : build error without gps subspec installed

- Android/doraemonkit/src/main/java/com/didichuxing/doraemonkit/ui/realtime/RealTimeChartIconPage.java
RealTimeChartIconPage 在onCreate回调时, 调用 getContext只会得到null，导致NPE;
因为getContext()的实现为
`    public Context getContext() {
if (mRootView != null) {
return mRootView.getContext();
} else {
return null;
}
}`
而此时,view还未创建
> fix(流量监控):Android-解决流量监控打开崩溃的异常

- Android/doraemonkit/src/main/java/com/didichuxing/doraemonkit/kit/weaknetwork/SpeedLimitRequestBody.java
解决由于BufferedSink已被close 后再次读取时导致的IllegalState异常
我们的项目中也添加了Interceptor 并且调用了 RequestBody 的WriteTo方法，由于Doraemonkit提前调用close()方法 ，导致我们项目自定义的Interceptor 读取时抛出 java.lang.IllegalStateException: closed 异常
BufferedSink 会由OkHttp 在 CallServerInterceptor 处理时调用close 释放资源, 不需要主动调用close方法。
> fix(模拟弱网):解决由于BufferedSink已被close 后再次读取时导致的IllegalState异常

- iOS/DoraemonKit/Src/Core/CommonUI/Oscillogram/DoraemonOscillogramWindow.h
- iOS/DoraemonKit/Src/Core/CommonUI/Oscillogram/DoraemonOscillogramWindow.m
- iOS/DoraemonKit/Src/Core/Plugin/CPU/DoraemonCPUViewController.m
- iOS/DoraemonKit/Src/Core/Plugin/FPS/DoraemonFPSViewController.m
- iOS/DoraemonKit/Src/Core/Plugin/Memory/DoraemonMemoryViewController.m
- iOS/DoraemonKit/Src/Core/Plugin/NetFlow/DoraemonNetFlowViewController.m
问题描述：在帧率、CPU、内存、流量页面关闭对应悬浮窗后 UISwitch 状态依然是打开状态
> fix: 性能检测： 帧率、CPU、内存、流量页面打开时关闭悬浮窗后 UISwitch 按钮状态未改变问题

- iOS/DoraemonKit/Src/Core/Manager/DoraemonManager.m
- iOS/DoraemonKit/Src/Core/Plugin/AllTest/DoraemonAllTestViewController.m
- iOS/DoraemonKit/Src/Core/Plugin/AllTest/Function/DoraemonAllTestManager.h
- iOS/DoraemonKit/Src/Core/Plugin/AllTest/Function/DoraemonAllTestManager.m
- iOS/DoraemonKit/Src/Core/Plugin/DeleteLocalData/DoraemonDeleteLocalDataViewController.m
1. fixed: `appVersion` 取错， 之前取到的是`build number`
2.fixed. 使用NSByteCountFormatter计算文件大小，之前的数值计算有误差
3. feat: 自定义测试页面，结束测试后，刷新按钮状态，防止再次进入该页面状态错误
4. feat: `DoraemonAllTestManager` 输出的log文件中的时间戳改为格式化后的字符串，提高可读性
> [iOS] 优化DoraemonAllTestManager

- iOS/DoraemonKit/Src/Core/Entry/DoraemonHomeEntry.m
layout warning
`the item width must be less than the width of the UICollectionView minus the section insets left and right values, minus the content insets left and right values.`
> fix: home entry view wrong layout value

- Android/doraemonkit/src/main/java/com/didichuxing/doraemonkit/kit/crash/CrashCaptureMainFragment.java
清理Crash日志, 界面显示的日志大小未及时刷新，再次进入界面才会刷新，会误以为没有删掉。
已测试
> 清理Crash日志, 界面显示的日志大小未及时刷新

- iOS/DoraemonKit/Src/Core/Manager/DoraemonManager.h
- iOS/DoraemonKit/Src/Core/Manager/DoraemonManager.m
- iOS/DoraemonKit/Src/Core/Plugin/NSUserDefaults/DoraemonNSUserDefaultsPlugin.h
- iOS/DoraemonKit/Src/Core/Plugin/NSUserDefaults/DoraemonNSUserDefaultsPlugin.m
- iOS/DoraemonKit/Src/Core/Plugin/NSUserDefaults/Model/DoraemonNSUserDefaultsModel.h
- iOS/DoraemonKit/Src/Core/Plugin/NSUserDefaults/Model/DoraemonNSUserDefaultsModel.m
- iOS/DoraemonKit/Src/Core/Plugin/NSUserDefaults/ViewControllers/DoraemonNSUserDefaultsEditViewController.h
- iOS/DoraemonKit/Src/Core/Plugin/NSUserDefaults/ViewControllers/DoraemonNSUserDefaultsEditViewController.m
- iOS/DoraemonKit/Src/Core/Plugin/NSUserDefaults/ViewControllers/DoraemonNSUserDefaultsViewController.h
- iOS/DoraemonKit/Src/Core/Plugin/NSUserDefaults/ViewControllers/DoraemonNSUserDefaultsViewController.m
开发、调试、自测、经常遇到需要查看NSUserDefaults数据的功能，增加一个工具用来查看、修改、清空 NSUserDefaults
优点： 
一眼看到NSUserDefaults 已存储状态（如是否登录）
可以修改NSUserDefaults已存储数据：不用每次测试其他状态时，通过代码修改NSUserDefaults
一键清空所有数据：如重置登录状态、重置所有标志位，方便QA测试，不用每次都卸载App来清空NSUserDefaults数据
> [iOS]: 增加查看、修改、清空 NSUserDefaults 数据功能

- iOS/DoraemonKit/Src/GPS/Function/DoraemonGPSMocker.m
DoraemonKit crash when start location under iOS 13.0.
The reason is CLLocationManager have two new delegate method need implement in DoraemonGPSMocker:
`- (void)locationManager:(CLLocationManager *)manager didRangeBeacons:(NSArray<CLBeacon *> *)beacons satisfyingConstraint:(CLBeaconIdentityConstraint *)beaconConstraint API_AVAILABLE(ios(13.0))`
`- (void)locationManager:(CLLocationManager *)manager didFailRangingBeaconsForConstraint:(CLBeaconIdentityConstraint *)beaconConstraint error:(NSError *)error API_AVAILABLE(ios(13.0))`
> [iOS] Add two methods on GMPMocker for iOS 13 

- iOS/Swift/DoKitSwift/Src/Plugins/Performance/Performance.swift
- iOS/Swift/DoKitSwiftDemo/DoKitSwiftDemo.xcodeproj/project.pbxproj
- Calculate CPU usage and memory usage.
- Suppress pod warning
````
[!] `<PBXNativeTarget name=`DoKitSwiftDemo` UUID=`0AE1029924693DAB006CA490`>` attempted to initialize an object with an unknown UUID. `69356E1B92816D4FCAB695A6` for attribute: `build_phases`. This can be the result of a merge and the unknown UUID is being discarded.
````
> Performance

- iOS/DoraemonKit/Src/Core/Plugin/Performance/LargeImageDetection/Function/UIImageView+DoraemonSDImage.m
问题①：在SD底层的`sd_internalSetImageWithURL`接口中可以获取到图片的元数据大小，没有必要使用非常耗时的`UIImageJPEGRepresentation()`来获取。
问题②：现在项目大部分人使用的是`SDAnimatedImageView`并且对应实现了`sd_setImageWithURL`方法, 如果 hook UIImageView的`sd_setImageWithURL`方法，并不能监听到`SDAnimatedImageView`图片的下载大小，而`sd_internalSetImageWithURL`可以兼容`UIImageView`和`SDAnimatedImageView`。
> Optimize fetch image data

- Android/java/buildSrc/src/main/kotlin/com/didichuxing/doraemonkit/plugin/DoKitPlugin.kt
- Android/java/buildSrc/src/main/kotlin/com/didichuxing/doraemonkit/plugin/ThirdLibInfo.kt
- Android/java/buildSrc/src/main/kotlin/com/didichuxing/doraemonkit/plugin/classtransformer/CommTransformer.kt
- Android/java/doraemonkit/src/main/java/com/didichuxing/doraemonkit/kit/sysinfo/ThirdLibInfoFragment.java
- Android/java/doraemonkit/src/main/java/com/didichuxing/doraemonkit/kit/sysinfo/ThirdLibInfoItemAdapter.java
- Android/java/doraemonkit/src/main/res/layout/dk_fragment_third_lib_info.xml
- Android/java/doraemonkit/src/main/res/layout/dk_fragment_weak_network.xml
- Android/java/doraemonkit/src/main/res/values-en-rUS/strings.xml
- Android/java/doraemonkit/src/main/res/values-zh-rCN/strings.xml
- Android/java/doraemonkit/src/main/res/values-zh-rTW/strings.xml
- Android/java/doraemonkit/src/main/res/values/strings.xml
去掉了原来的搜索按钮，输入文本会即时搜索并且不区分大小写
增加按名称和按大小排序，大小排序能更快的找出占用最大的库
> 第三方库信息列表支持实时搜索、排序

- iOS/DoraemonKit/Src/Core/Cache/DoraemonCacheManager.m
首次安装进入哆啦A梦首页，自定义模块跑到了最下面，当进入自定义排序页面后，自定义模块才会到最上面。
此处应该保证，自定义模块任何情况下都应该在第一行
> feat:修复首次安装自定义模块顺序不在第一行的问题(在没有进入自定义排序的情况下)

- Web/packages/web/src/plugins/resources/css/var.less
- Web/packages/web/src/plugins/resources/index.js
- Web/packages/web/src/plugins/resources/js/resources.js
- Web/packages/web/src/plugins/resources/main.vue
- Web/packages/web/src/plugins/resources/resource-container.vue
- Web/packages/web/src/plugins/resources/resource-item.vue
- Web/packages/web/src/plugins/resources/resource-tap.vue
DoKit For Web 的 resources（资源查看）插件
功能：
分别展示css、script、img、其他类型资源。
默认显示所有资源的url，点击url可显示详细信息，例如initiatorType，css、script类型的详细代码，img类型的缩略图和图片尺寸
原理：
通过window.performance.getEntriesByType("resource")读取所有页面上的所有资源，产生resourceList，根据initiatorType和一些特判规则将资源分为css、script、img、other四类，展示在四个标签页中。
在每次打开“资源查看”插件时，更新resourceList并去重。
在生成resourceList的时候，获取所有图片的base64值并存储，在需要显示图片详情时通过base64访问，减少网络请求。
在需要显示css或script代码详情时，请求获取文本，并显示为带行号和缩进的样式。
作者：Zhang Xinyu
截图：
> 【DoKit&北大开源实践】-【DoKit For Web】- 资源查看

- Web/packages/web/src/plugins/h5-door/ToolH5Door.vue
- Web/packages/web/src/plugins/h5-door/index.js
**功能描述**
输入url地址，完成任意页面的跳转
**功能原理**
核心跳转：将`<input>`与vue中的url数据绑定，利用`window.open`实现跳转
历史记录：利用对象数组存储每一次跳转的url，在页面中用`<li>`标签展示；同时支持对单条记录的删除和载入操作；正则化对url进行修正
数据缓存：利用函数`window.localStorge`完成数据缓存与读取，保证每次重新进入页面时保留以前的历史信息
页面布局：利用`flex`优化布局，避免网址过长等问题带来的影响
**功能截图**
无历史
历史记录
flex布局
> 【DoKit&北大开源实践】-【DoKit For Web】- H5任意门

- miniapp/src/components/debug/debug.js
- miniapp/src/components/debug/debug.wxss
- miniapp/src/components/pagedoor/pagedoor.js
- miniapp/src/components/pagedoor/pagedoor.json
- miniapp/src/components/pagedoor/pagedoor.wxml
- miniapp/src/components/pagedoor/pagedoor.wxss
- miniapp/src/index/index.json
- miniapp/src/index/index.wxml
**功能描述：**
允许用户很方便的测试以不同方式并携带任意参数进入某一页面的效果
- 通过自动填写或手动输入的方式确定页面路径
- 支持动态添加参数
- 支持四种路由方式（`navigateTo` 、`redirectTo`、`reLaunch`、`switchTab` ）
**实现原理：**
通过`__wxConfig` 自动获取项目全局的页面路径，将路径与参数拼接后调用官方API实现不同方式路由
（注：由于`wx.switchTab` 不支持携带参数，因此使用Tab切换方式时输入的参数会被忽略）
**功能截图：**
> 【DoKit&北大开源实践】-【DoKit For miniapp】- page任意门

- Android/config.gradle
- Android/dokit-gps-mock/src/main/java/com/didichuxing/doraemonkit/gps_mock/common/BdMapRouteData.java
- Android/dokit-gps-mock/src/main/java/com/didichuxing/doraemonkit/gps_mock/gpsmock/GpsMockFragment.java
- Android/dokit-gps-mock/src/main/java/com/didichuxing/doraemonkit/gps_mock/gpsmock/GpsMockManager.java
- Android/dokit-gps-mock/src/main/java/com/didichuxing/doraemonkit/gps_mock/widget/DrivingRouteOverlay.java
- Android/dokit-gps-mock/src/main/java/com/didichuxing/doraemonkit/gps_mock/widget/OverlayManager.java
- Android/dokit-gps-mock/src/main/res/layout/dk_fragment_gps_mock.xml
- Android/dokit-gps-mock/src/main/res/values-en-rCN/strings.xml
- Android/dokit-gps-mock/src/main/res/values-zh-rTW/strings.xml
- Android/dokit-gps-mock/src/main/res/values-zh-rUS/strings.xml
- Android/dokit-gps-mock/src/main/res/values/strings.xml
- Android/dokit-plugin/src/main/kotlin/com/didichuxing/doraemonkit/plugin/classtransformer/CommClassTransformer.kt
- Android/dokit/src/main/java/com/didichuxing/doraemonkit/config/GpsMockConfig.java
- Android/dokit/src/main/java/com/didichuxing/doraemonkit/constant/SharedPrefsKey.java
> feat(Android):增加心跳丢失模拟功能.
